apiVersion: applications.app.io/v1beta1
kind: Application
metadata:
  name: application-sample
spec:
  revisionHistoryLimit: 10
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          ccnp.cib/app: nginx-deploy
        name: nginx-deploy
        namespace: l002x0
      spec:
        replicas: 2
        selector:
          matchLabels:
            ccnp.cib/component: nginx-deploy
        template:
          metadata:
            labels:
              ccnp.cib/app: nginx-deploy
              ccnp.cib/component: nginx-deploy
          spec:
            containers:
              - image: nginx:latest
                imagePullPolicy: Always
                name: nginx-deploy
                resources:
                  limits:
                    cpu: 128m
                    memory: "67108864"
                  requests:
                    cpu: 64m
                    memory: "67108864"
    - apiVersion: v1
      kind: Service
      metadata:
        labels:
          ccnp.cib/app: nginx-deploy
        name: nginx-deploy
        namespace: l002x0
      spec:
        ports:
          - name: nginx-deploy
            port: 80
            protocol: TCP
            targetPort: 80
        selector:
          ccnp.cib/component: nginx-deploy
        sessionAffinity: None
        type: ClusterIP
  selector: {}
  descriptor:
    type: "nginx"
    keywords:
      - "cms"
      - "blog"
    links:
      - description: About
        url: "https://wordpress.org/"
      - description: Web Server Dashboard
        url: "https://metrics/internal/wordpress-01/web-app"
      - description: Mysql Dashboard
        url: "https://metrics/internal/wordpress-01/mysql"
    version: "4.9.4"
    description: "WordPress is open source software you can use to create a beautiful website, blog, or app."
    icons:
      - src: "https://s.w.org/style/images/about/WordPress-logotype-wmark.png"
        type: "image/png"
        size: "1000x1000"
      - src: "https://s.w.org/style/images/about/WordPress-logotype-standard.png"
        type: "image/png"
        size: "2000x680"
    maintainers:
      - name: Wordpress Dev
        email: dev@wordpress.org
    owners:
      - name: Wordpress Admin
        email: admin@wordpress.org


